version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.0.0/terraform_1.0.0_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
  pre_build:
    commands:
      - terraform --version
      - terraform init
  build:
    commands:
      - terraform plan
  post_build:
    commands:
      - terraform apply -auto-approve